// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/archer/models"
)

// GetServiceServiceIDEndpointsHandlerFunc turns a function with the right signature into a get service service ID endpoints handler
type GetServiceServiceIDEndpointsHandlerFunc func(GetServiceServiceIDEndpointsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetServiceServiceIDEndpointsHandlerFunc) Handle(params GetServiceServiceIDEndpointsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetServiceServiceIDEndpointsHandler interface for that can handle valid get service service ID endpoints params
type GetServiceServiceIDEndpointsHandler interface {
	Handle(GetServiceServiceIDEndpointsParams, interface{}) middleware.Responder
}

// NewGetServiceServiceIDEndpoints creates a new http.Handler for the get service service ID endpoints operation
func NewGetServiceServiceIDEndpoints(ctx *middleware.Context, handler GetServiceServiceIDEndpointsHandler) *GetServiceServiceIDEndpoints {
	return &GetServiceServiceIDEndpoints{Context: ctx, Handler: handler}
}

/*
	GetServiceServiceIDEndpoints swagger:route GET /service/{service_id}/endpoints Service getServiceServiceIdEndpoints

# List service endpoints consumers

Provides a list of service consumers (endpoints).

This list can be used to accept or reject requests, or disable active endpoints.
Rejected endpoints will be cleaned up after a specific time.
*/
type GetServiceServiceIDEndpoints struct {
	Context *middleware.Context
	Handler GetServiceServiceIDEndpointsHandler
}

func (o *GetServiceServiceIDEndpoints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetServiceServiceIDEndpointsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetServiceServiceIDEndpointsOKBody get service service ID endpoints o k body
//
// swagger:model GetServiceServiceIDEndpointsOKBody
type GetServiceServiceIDEndpointsOKBody struct {

	// items
	Items []*models.EndpointConsumer `json:"items"`

	// links
	Links []*models.Link `json:"links,omitempty"`
}

// Validate validates this get service service ID endpoints o k body
func (o *GetServiceServiceIDEndpointsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServiceServiceIDEndpointsOKBody) validateItems(formats strfmt.Registry) error {
	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getServiceServiceIdEndpointsOK" + "." + "items" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getServiceServiceIdEndpointsOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetServiceServiceIDEndpointsOKBody) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	for i := 0; i < len(o.Links); i++ {
		if swag.IsZero(o.Links[i]) { // not required
			continue
		}

		if o.Links[i] != nil {
			if err := o.Links[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getServiceServiceIdEndpointsOK" + "." + "links" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getServiceServiceIdEndpointsOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get service service ID endpoints o k body based on the context it is used
func (o *GetServiceServiceIDEndpointsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServiceServiceIDEndpointsOKBody) contextValidateItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Items); i++ {

		if o.Items[i] != nil {

			if swag.IsZero(o.Items[i]) { // not required
				return nil
			}

			if err := o.Items[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getServiceServiceIdEndpointsOK" + "." + "items" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getServiceServiceIdEndpointsOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetServiceServiceIDEndpointsOKBody) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Links); i++ {

		if o.Links[i] != nil {

			if swag.IsZero(o.Links[i]) { // not required
				return nil
			}

			if err := o.Links[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getServiceServiceIdEndpointsOK" + "." + "links" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getServiceServiceIdEndpointsOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetServiceServiceIDEndpointsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetServiceServiceIDEndpointsOKBody) UnmarshalBinary(b []byte) error {
	var res GetServiceServiceIDEndpointsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
