// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/archer/models"
)

// PostServiceOKCode is the HTTP code returned for type PostServiceOK
const PostServiceOKCode int = 200

/*
PostServiceOK Service

swagger:response postServiceOK
*/
type PostServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewPostServiceOK creates PostServiceOK with default headers values
func NewPostServiceOK() *PostServiceOK {

	return &PostServiceOK{}
}

// WithPayload adds the payload to the post service o k response
func (o *PostServiceOK) WithPayload(payload *models.Service) *PostServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post service o k response
func (o *PostServiceOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostServiceBadRequestCode is the HTTP code returned for type PostServiceBadRequest
const PostServiceBadRequestCode int = 400

/*
PostServiceBadRequest Validation Error

swagger:response postServiceBadRequest
*/
type PostServiceBadRequest struct {
}

// NewPostServiceBadRequest creates PostServiceBadRequest with default headers values
func NewPostServiceBadRequest() *PostServiceBadRequest {

	return &PostServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostServiceConflictCode is the HTTP code returned for type PostServiceConflict
const PostServiceConflictCode int = 409

/*
PostServiceConflict Duplicate entry

swagger:response postServiceConflict
*/
type PostServiceConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostServiceConflict creates PostServiceConflict with default headers values
func NewPostServiceConflict() *PostServiceConflict {

	return &PostServiceConflict{}
}

// WithPayload adds the payload to the post service conflict response
func (o *PostServiceConflict) WithPayload(payload *models.Error) *PostServiceConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post service conflict response
func (o *PostServiceConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostServiceConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
