// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package service

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostServiceServiceIDMigrateHandlerFunc turns a function with the right signature into a post service service ID migrate handler
type PostServiceServiceIDMigrateHandlerFunc func(PostServiceServiceIDMigrateParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn PostServiceServiceIDMigrateHandlerFunc) Handle(params PostServiceServiceIDMigrateParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// PostServiceServiceIDMigrateHandler interface for that can handle valid post service service ID migrate params
type PostServiceServiceIDMigrateHandler interface {
	Handle(PostServiceServiceIDMigrateParams, any) middleware.Responder
}

// NewPostServiceServiceIDMigrate creates a new http.Handler for the post service service ID migrate operation
func NewPostServiceServiceIDMigrate(ctx *middleware.Context, handler PostServiceServiceIDMigrateHandler) *PostServiceServiceIDMigrate {
	return &PostServiceServiceIDMigrate{Context: ctx, Handler: handler}
}

/*
	PostServiceServiceIDMigrate swagger:route POST /service/{service_id}/migrate Service postServiceServiceIdMigrate

# Migrate service to a different agent

Migrates a service from its current agent to a different agent.
The service will be set to PENDING_UPDATE status and all its endpoints
will be re-provisioned on the new agent.

If target_host is not specified, the least-loaded agent in the same
availability zone is automatically selected.
*/
type PostServiceServiceIDMigrate struct {
	Context *middleware.Context
	Handler PostServiceServiceIDMigrateHandler
}

func (o *PostServiceServiceIDMigrate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostServiceServiceIDMigrateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostServiceServiceIDMigrateBody post service service ID migrate body
//
// swagger:model PostServiceServiceIDMigrateBody
type PostServiceServiceIDMigrateBody struct {

	// Target agent hostname. If not specified, least-loaded agent is selected.
	TargetHost string `json:"target_host,omitempty"`
}

// Validate validates this post service service ID migrate body
func (o *PostServiceServiceIDMigrateBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post service service ID migrate body based on context it is used
func (o *PostServiceServiceIDMigrateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostServiceServiceIDMigrateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostServiceServiceIDMigrateBody) UnmarshalBinary(b []byte) error {
	var res PostServiceServiceIDMigrateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
