// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/archer/models"
)

// PutServiceServiceIDRejectEndpointsOKCode is the HTTP code returned for type PutServiceServiceIDRejectEndpointsOK
const PutServiceServiceIDRejectEndpointsOKCode int = 200

/*
PutServiceServiceIDRejectEndpointsOK Ok

swagger:response putServiceServiceIdRejectEndpointsOK
*/
type PutServiceServiceIDRejectEndpointsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.EndpointConsumer `json:"body,omitempty"`
}

// NewPutServiceServiceIDRejectEndpointsOK creates PutServiceServiceIDRejectEndpointsOK with default headers values
func NewPutServiceServiceIDRejectEndpointsOK() *PutServiceServiceIDRejectEndpointsOK {

	return &PutServiceServiceIDRejectEndpointsOK{}
}

// WithPayload adds the payload to the put service service Id reject endpoints o k response
func (o *PutServiceServiceIDRejectEndpointsOK) WithPayload(payload []*models.EndpointConsumer) *PutServiceServiceIDRejectEndpointsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put service service Id reject endpoints o k response
func (o *PutServiceServiceIDRejectEndpointsOK) SetPayload(payload []*models.EndpointConsumer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutServiceServiceIDRejectEndpointsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.EndpointConsumer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutServiceServiceIDRejectEndpointsBadRequestCode is the HTTP code returned for type PutServiceServiceIDRejectEndpointsBadRequest
const PutServiceServiceIDRejectEndpointsBadRequestCode int = 400

/*
PutServiceServiceIDRejectEndpointsBadRequest Must declare at least one, endpoint_id(s) or project_id(s)

swagger:response putServiceServiceIdRejectEndpointsBadRequest
*/
type PutServiceServiceIDRejectEndpointsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutServiceServiceIDRejectEndpointsBadRequest creates PutServiceServiceIDRejectEndpointsBadRequest with default headers values
func NewPutServiceServiceIDRejectEndpointsBadRequest() *PutServiceServiceIDRejectEndpointsBadRequest {

	return &PutServiceServiceIDRejectEndpointsBadRequest{}
}

// WithPayload adds the payload to the put service service Id reject endpoints bad request response
func (o *PutServiceServiceIDRejectEndpointsBadRequest) WithPayload(payload *models.Error) *PutServiceServiceIDRejectEndpointsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put service service Id reject endpoints bad request response
func (o *PutServiceServiceIDRejectEndpointsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutServiceServiceIDRejectEndpointsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutServiceServiceIDRejectEndpointsForbiddenCode is the HTTP code returned for type PutServiceServiceIDRejectEndpointsForbidden
const PutServiceServiceIDRejectEndpointsForbiddenCode int = 403

/*
PutServiceServiceIDRejectEndpointsForbidden Forbidden

swagger:response putServiceServiceIdRejectEndpointsForbidden
*/
type PutServiceServiceIDRejectEndpointsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutServiceServiceIDRejectEndpointsForbidden creates PutServiceServiceIDRejectEndpointsForbidden with default headers values
func NewPutServiceServiceIDRejectEndpointsForbidden() *PutServiceServiceIDRejectEndpointsForbidden {

	return &PutServiceServiceIDRejectEndpointsForbidden{}
}

// WithPayload adds the payload to the put service service Id reject endpoints forbidden response
func (o *PutServiceServiceIDRejectEndpointsForbidden) WithPayload(payload *models.Error) *PutServiceServiceIDRejectEndpointsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put service service Id reject endpoints forbidden response
func (o *PutServiceServiceIDRejectEndpointsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutServiceServiceIDRejectEndpointsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutServiceServiceIDRejectEndpointsNotFoundCode is the HTTP code returned for type PutServiceServiceIDRejectEndpointsNotFound
const PutServiceServiceIDRejectEndpointsNotFoundCode int = 404

/*
PutServiceServiceIDRejectEndpointsNotFound Not Found

swagger:response putServiceServiceIdRejectEndpointsNotFound
*/
type PutServiceServiceIDRejectEndpointsNotFound struct {
}

// NewPutServiceServiceIDRejectEndpointsNotFound creates PutServiceServiceIDRejectEndpointsNotFound with default headers values
func NewPutServiceServiceIDRejectEndpointsNotFound() *PutServiceServiceIDRejectEndpointsNotFound {

	return &PutServiceServiceIDRejectEndpointsNotFound{}
}

// WriteResponse to the client
func (o *PutServiceServiceIDRejectEndpointsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
