// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteRbacPoliciesRbacPolicyIDReader is a Reader for the DeleteRbacPoliciesRbacPolicyID structure.
type DeleteRbacPoliciesRbacPolicyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRbacPoliciesRbacPolicyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRbacPoliciesRbacPolicyIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteRbacPoliciesRbacPolicyIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRbacPoliciesRbacPolicyIDNoContent creates a DeleteRbacPoliciesRbacPolicyIDNoContent with default headers values
func NewDeleteRbacPoliciesRbacPolicyIDNoContent() *DeleteRbacPoliciesRbacPolicyIDNoContent {
	return &DeleteRbacPoliciesRbacPolicyIDNoContent{}
}

/*
DeleteRbacPoliciesRbacPolicyIDNoContent describes a response with status code 204, with default header values.

Resource successfully deleted.
*/
type DeleteRbacPoliciesRbacPolicyIDNoContent struct {
}

// IsSuccess returns true when this delete rbac policies rbac policy Id no content response has a 2xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete rbac policies rbac policy Id no content response has a 3xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete rbac policies rbac policy Id no content response has a 4xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete rbac policies rbac policy Id no content response has a 5xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete rbac policies rbac policy Id no content response a status code equal to that given
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete rbac policies rbac policy Id no content response
func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) Code() int {
	return 204
}

func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /rbac-policies/{rbac_policy_id}][%d] deleteRbacPoliciesRbacPolicyIdNoContent ", 204)
}

func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /rbac-policies/{rbac_policy_id}][%d] deleteRbacPoliciesRbacPolicyIdNoContent ", 204)
}

func (o *DeleteRbacPoliciesRbacPolicyIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRbacPoliciesRbacPolicyIDNotFound creates a DeleteRbacPoliciesRbacPolicyIDNotFound with default headers values
func NewDeleteRbacPoliciesRbacPolicyIDNotFound() *DeleteRbacPoliciesRbacPolicyIDNotFound {
	return &DeleteRbacPoliciesRbacPolicyIDNotFound{}
}

/*
DeleteRbacPoliciesRbacPolicyIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteRbacPoliciesRbacPolicyIDNotFound struct {
}

// IsSuccess returns true when this delete rbac policies rbac policy Id not found response has a 2xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete rbac policies rbac policy Id not found response has a 3xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete rbac policies rbac policy Id not found response has a 4xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete rbac policies rbac policy Id not found response has a 5xx status code
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete rbac policies rbac policy Id not found response a status code equal to that given
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete rbac policies rbac policy Id not found response
func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) Code() int {
	return 404
}

func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /rbac-policies/{rbac_policy_id}][%d] deleteRbacPoliciesRbacPolicyIdNotFound ", 404)
}

func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /rbac-policies/{rbac_policy_id}][%d] deleteRbacPoliciesRbacPolicyIdNotFound ", 404)
}

func (o *DeleteRbacPoliciesRbacPolicyIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
