// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRbacPoliciesRbacPolicyIDParams creates a new GetRbacPoliciesRbacPolicyIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRbacPoliciesRbacPolicyIDParams() *GetRbacPoliciesRbacPolicyIDParams {
	return &GetRbacPoliciesRbacPolicyIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRbacPoliciesRbacPolicyIDParamsWithTimeout creates a new GetRbacPoliciesRbacPolicyIDParams object
// with the ability to set a timeout on a request.
func NewGetRbacPoliciesRbacPolicyIDParamsWithTimeout(timeout time.Duration) *GetRbacPoliciesRbacPolicyIDParams {
	return &GetRbacPoliciesRbacPolicyIDParams{
		timeout: timeout,
	}
}

// NewGetRbacPoliciesRbacPolicyIDParamsWithContext creates a new GetRbacPoliciesRbacPolicyIDParams object
// with the ability to set a context for a request.
func NewGetRbacPoliciesRbacPolicyIDParamsWithContext(ctx context.Context) *GetRbacPoliciesRbacPolicyIDParams {
	return &GetRbacPoliciesRbacPolicyIDParams{
		Context: ctx,
	}
}

// NewGetRbacPoliciesRbacPolicyIDParamsWithHTTPClient creates a new GetRbacPoliciesRbacPolicyIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRbacPoliciesRbacPolicyIDParamsWithHTTPClient(client *http.Client) *GetRbacPoliciesRbacPolicyIDParams {
	return &GetRbacPoliciesRbacPolicyIDParams{
		HTTPClient: client,
	}
}

/*
GetRbacPoliciesRbacPolicyIDParams contains all the parameters to send to the API endpoint

	for the get rbac policies rbac policy ID operation.

	Typically these are written to a http.Request.
*/
type GetRbacPoliciesRbacPolicyIDParams struct {

	/* RbacPolicyID.

	   The UUID of the RBAC policy.

	   Format: uuid
	*/
	RbacPolicyID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rbac policies rbac policy ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRbacPoliciesRbacPolicyIDParams) WithDefaults() *GetRbacPoliciesRbacPolicyIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rbac policies rbac policy ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRbacPoliciesRbacPolicyIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) WithTimeout(timeout time.Duration) *GetRbacPoliciesRbacPolicyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) WithContext(ctx context.Context) *GetRbacPoliciesRbacPolicyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) WithHTTPClient(client *http.Client) *GetRbacPoliciesRbacPolicyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRbacPolicyID adds the rbacPolicyID to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) WithRbacPolicyID(rbacPolicyID strfmt.UUID) *GetRbacPoliciesRbacPolicyIDParams {
	o.SetRbacPolicyID(rbacPolicyID)
	return o
}

// SetRbacPolicyID adds the rbacPolicyId to the get rbac policies rbac policy ID params
func (o *GetRbacPoliciesRbacPolicyIDParams) SetRbacPolicyID(rbacPolicyID strfmt.UUID) {
	o.RbacPolicyID = rbacPolicyID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRbacPoliciesRbacPolicyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rbac_policy_id
	if err := r.SetPathParam("rbac_policy_id", o.RbacPolicyID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
