// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/archer/models"
)

// DeleteQuotasProjectIDReader is a Reader for the DeleteQuotasProjectID structure.
type DeleteQuotasProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteQuotasProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteQuotasProjectIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteQuotasProjectIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteQuotasProjectIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteQuotasProjectIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteQuotasProjectIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /quotas/{project_id}] DeleteQuotasProjectID", response, response.Code())
	}
}

// NewDeleteQuotasProjectIDNoContent creates a DeleteQuotasProjectIDNoContent with default headers values
func NewDeleteQuotasProjectIDNoContent() *DeleteQuotasProjectIDNoContent {
	return &DeleteQuotasProjectIDNoContent{}
}

/*
DeleteQuotasProjectIDNoContent describes a response with status code 204, with default header values.

Resource successfully reset
*/
type DeleteQuotasProjectIDNoContent struct {
}

// IsSuccess returns true when this delete quotas project Id no content response has a 2xx status code
func (o *DeleteQuotasProjectIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete quotas project Id no content response has a 3xx status code
func (o *DeleteQuotasProjectIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete quotas project Id no content response has a 4xx status code
func (o *DeleteQuotasProjectIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete quotas project Id no content response has a 5xx status code
func (o *DeleteQuotasProjectIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete quotas project Id no content response a status code equal to that given
func (o *DeleteQuotasProjectIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete quotas project Id no content response
func (o *DeleteQuotasProjectIDNoContent) Code() int {
	return 204
}

func (o *DeleteQuotasProjectIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdNoContent", 204)
}

func (o *DeleteQuotasProjectIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdNoContent", 204)
}

func (o *DeleteQuotasProjectIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotasProjectIDUnauthorized creates a DeleteQuotasProjectIDUnauthorized with default headers values
func NewDeleteQuotasProjectIDUnauthorized() *DeleteQuotasProjectIDUnauthorized {
	return &DeleteQuotasProjectIDUnauthorized{}
}

/*
DeleteQuotasProjectIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteQuotasProjectIDUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete quotas project Id unauthorized response has a 2xx status code
func (o *DeleteQuotasProjectIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete quotas project Id unauthorized response has a 3xx status code
func (o *DeleteQuotasProjectIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete quotas project Id unauthorized response has a 4xx status code
func (o *DeleteQuotasProjectIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete quotas project Id unauthorized response has a 5xx status code
func (o *DeleteQuotasProjectIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete quotas project Id unauthorized response a status code equal to that given
func (o *DeleteQuotasProjectIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete quotas project Id unauthorized response
func (o *DeleteQuotasProjectIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteQuotasProjectIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdUnauthorized %s", 401, payload)
}

func (o *DeleteQuotasProjectIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdUnauthorized %s", 401, payload)
}

func (o *DeleteQuotasProjectIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteQuotasProjectIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteQuotasProjectIDForbidden creates a DeleteQuotasProjectIDForbidden with default headers values
func NewDeleteQuotasProjectIDForbidden() *DeleteQuotasProjectIDForbidden {
	return &DeleteQuotasProjectIDForbidden{}
}

/*
DeleteQuotasProjectIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteQuotasProjectIDForbidden struct {
}

// IsSuccess returns true when this delete quotas project Id forbidden response has a 2xx status code
func (o *DeleteQuotasProjectIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete quotas project Id forbidden response has a 3xx status code
func (o *DeleteQuotasProjectIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete quotas project Id forbidden response has a 4xx status code
func (o *DeleteQuotasProjectIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete quotas project Id forbidden response has a 5xx status code
func (o *DeleteQuotasProjectIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete quotas project Id forbidden response a status code equal to that given
func (o *DeleteQuotasProjectIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete quotas project Id forbidden response
func (o *DeleteQuotasProjectIDForbidden) Code() int {
	return 403
}

func (o *DeleteQuotasProjectIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdForbidden", 403)
}

func (o *DeleteQuotasProjectIDForbidden) String() string {
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdForbidden", 403)
}

func (o *DeleteQuotasProjectIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotasProjectIDNotFound creates a DeleteQuotasProjectIDNotFound with default headers values
func NewDeleteQuotasProjectIDNotFound() *DeleteQuotasProjectIDNotFound {
	return &DeleteQuotasProjectIDNotFound{}
}

/*
DeleteQuotasProjectIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteQuotasProjectIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete quotas project Id not found response has a 2xx status code
func (o *DeleteQuotasProjectIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete quotas project Id not found response has a 3xx status code
func (o *DeleteQuotasProjectIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete quotas project Id not found response has a 4xx status code
func (o *DeleteQuotasProjectIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete quotas project Id not found response has a 5xx status code
func (o *DeleteQuotasProjectIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete quotas project Id not found response a status code equal to that given
func (o *DeleteQuotasProjectIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete quotas project Id not found response
func (o *DeleteQuotasProjectIDNotFound) Code() int {
	return 404
}

func (o *DeleteQuotasProjectIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdNotFound %s", 404, payload)
}

func (o *DeleteQuotasProjectIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdNotFound %s", 404, payload)
}

func (o *DeleteQuotasProjectIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteQuotasProjectIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteQuotasProjectIDUnprocessableEntity creates a DeleteQuotasProjectIDUnprocessableEntity with default headers values
func NewDeleteQuotasProjectIDUnprocessableEntity() *DeleteQuotasProjectIDUnprocessableEntity {
	return &DeleteQuotasProjectIDUnprocessableEntity{}
}

/*
DeleteQuotasProjectIDUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Content
*/
type DeleteQuotasProjectIDUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete quotas project Id unprocessable entity response has a 2xx status code
func (o *DeleteQuotasProjectIDUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete quotas project Id unprocessable entity response has a 3xx status code
func (o *DeleteQuotasProjectIDUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete quotas project Id unprocessable entity response has a 4xx status code
func (o *DeleteQuotasProjectIDUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete quotas project Id unprocessable entity response has a 5xx status code
func (o *DeleteQuotasProjectIDUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete quotas project Id unprocessable entity response a status code equal to that given
func (o *DeleteQuotasProjectIDUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete quotas project Id unprocessable entity response
func (o *DeleteQuotasProjectIDUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteQuotasProjectIDUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdUnprocessableEntity %s", 422, payload)
}

func (o *DeleteQuotasProjectIDUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /quotas/{project_id}][%d] deleteQuotasProjectIdUnprocessableEntity %s", 422, payload)
}

func (o *DeleteQuotasProjectIDUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteQuotasProjectIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
