// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/archer/models"
)

// GetEndpointEndpointIDReader is a Reader for the GetEndpointEndpointID structure.
type GetEndpointEndpointIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEndpointEndpointIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEndpointEndpointIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetEndpointEndpointIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEndpointEndpointIDOK creates a GetEndpointEndpointIDOK with default headers values
func NewGetEndpointEndpointIDOK() *GetEndpointEndpointIDOK {
	return &GetEndpointEndpointIDOK{}
}

/*
GetEndpointEndpointIDOK describes a response with status code 200, with default header values.

An endpoint detail.
*/
type GetEndpointEndpointIDOK struct {
	Payload *models.Endpoint
}

// IsSuccess returns true when this get endpoint endpoint Id o k response has a 2xx status code
func (o *GetEndpointEndpointIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get endpoint endpoint Id o k response has a 3xx status code
func (o *GetEndpointEndpointIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get endpoint endpoint Id o k response has a 4xx status code
func (o *GetEndpointEndpointIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get endpoint endpoint Id o k response has a 5xx status code
func (o *GetEndpointEndpointIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get endpoint endpoint Id o k response a status code equal to that given
func (o *GetEndpointEndpointIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get endpoint endpoint Id o k response
func (o *GetEndpointEndpointIDOK) Code() int {
	return 200
}

func (o *GetEndpointEndpointIDOK) Error() string {
	return fmt.Sprintf("[GET /endpoint/{endpoint_id}][%d] getEndpointEndpointIdOK  %+v", 200, o.Payload)
}

func (o *GetEndpointEndpointIDOK) String() string {
	return fmt.Sprintf("[GET /endpoint/{endpoint_id}][%d] getEndpointEndpointIdOK  %+v", 200, o.Payload)
}

func (o *GetEndpointEndpointIDOK) GetPayload() *models.Endpoint {
	return o.Payload
}

func (o *GetEndpointEndpointIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Endpoint)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEndpointEndpointIDNotFound creates a GetEndpointEndpointIDNotFound with default headers values
func NewGetEndpointEndpointIDNotFound() *GetEndpointEndpointIDNotFound {
	return &GetEndpointEndpointIDNotFound{}
}

/*
GetEndpointEndpointIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetEndpointEndpointIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get endpoint endpoint Id not found response has a 2xx status code
func (o *GetEndpointEndpointIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get endpoint endpoint Id not found response has a 3xx status code
func (o *GetEndpointEndpointIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get endpoint endpoint Id not found response has a 4xx status code
func (o *GetEndpointEndpointIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get endpoint endpoint Id not found response has a 5xx status code
func (o *GetEndpointEndpointIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get endpoint endpoint Id not found response a status code equal to that given
func (o *GetEndpointEndpointIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get endpoint endpoint Id not found response
func (o *GetEndpointEndpointIDNotFound) Code() int {
	return 404
}

func (o *GetEndpointEndpointIDNotFound) Error() string {
	return fmt.Sprintf("[GET /endpoint/{endpoint_id}][%d] getEndpointEndpointIdNotFound  %+v", 404, o.Payload)
}

func (o *GetEndpointEndpointIDNotFound) String() string {
	return fmt.Sprintf("[GET /endpoint/{endpoint_id}][%d] getEndpointEndpointIdNotFound  %+v", 404, o.Payload)
}

func (o *GetEndpointEndpointIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetEndpointEndpointIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
