// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/archer/models"
)

// NewPostEndpointParams creates a new PostEndpointParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostEndpointParams() *PostEndpointParams {
	return &PostEndpointParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostEndpointParamsWithTimeout creates a new PostEndpointParams object
// with the ability to set a timeout on a request.
func NewPostEndpointParamsWithTimeout(timeout time.Duration) *PostEndpointParams {
	return &PostEndpointParams{
		timeout: timeout,
	}
}

// NewPostEndpointParamsWithContext creates a new PostEndpointParams object
// with the ability to set a context for a request.
func NewPostEndpointParamsWithContext(ctx context.Context) *PostEndpointParams {
	return &PostEndpointParams{
		Context: ctx,
	}
}

// NewPostEndpointParamsWithHTTPClient creates a new PostEndpointParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostEndpointParamsWithHTTPClient(client *http.Client) *PostEndpointParams {
	return &PostEndpointParams{
		HTTPClient: client,
	}
}

/*
PostEndpointParams contains all the parameters to send to the API endpoint

	for the post endpoint operation.

	Typically these are written to a http.Request.
*/
type PostEndpointParams struct {

	/* Body.

	   Service and target network to inject. Only one of `target_network`, `target_subnet` or `target_port` must be specified.
	*/
	Body *models.Endpoint

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post endpoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEndpointParams) WithDefaults() *PostEndpointParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post endpoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEndpointParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post endpoint params
func (o *PostEndpointParams) WithTimeout(timeout time.Duration) *PostEndpointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post endpoint params
func (o *PostEndpointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post endpoint params
func (o *PostEndpointParams) WithContext(ctx context.Context) *PostEndpointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post endpoint params
func (o *PostEndpointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post endpoint params
func (o *PostEndpointParams) WithHTTPClient(client *http.Client) *PostEndpointParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post endpoint params
func (o *PostEndpointParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post endpoint params
func (o *PostEndpointParams) WithBody(body *models.Endpoint) *PostEndpointParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post endpoint params
func (o *PostEndpointParams) SetBody(body *models.Endpoint) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostEndpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
