// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutEndpointEndpointIDParams creates a new PutEndpointEndpointIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutEndpointEndpointIDParams() *PutEndpointEndpointIDParams {
	return &PutEndpointEndpointIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutEndpointEndpointIDParamsWithTimeout creates a new PutEndpointEndpointIDParams object
// with the ability to set a timeout on a request.
func NewPutEndpointEndpointIDParamsWithTimeout(timeout time.Duration) *PutEndpointEndpointIDParams {
	return &PutEndpointEndpointIDParams{
		timeout: timeout,
	}
}

// NewPutEndpointEndpointIDParamsWithContext creates a new PutEndpointEndpointIDParams object
// with the ability to set a context for a request.
func NewPutEndpointEndpointIDParamsWithContext(ctx context.Context) *PutEndpointEndpointIDParams {
	return &PutEndpointEndpointIDParams{
		Context: ctx,
	}
}

// NewPutEndpointEndpointIDParamsWithHTTPClient creates a new PutEndpointEndpointIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutEndpointEndpointIDParamsWithHTTPClient(client *http.Client) *PutEndpointEndpointIDParams {
	return &PutEndpointEndpointIDParams{
		HTTPClient: client,
	}
}

/*
PutEndpointEndpointIDParams contains all the parameters to send to the API endpoint

	for the put endpoint endpoint ID operation.

	Typically these are written to a http.Request.
*/
type PutEndpointEndpointIDParams struct {

	/* Body.

	   Endpoint object that needs to be updated
	*/
	Body PutEndpointEndpointIDBody

	/* EndpointID.

	   The UUID of the endpoint

	   Format: uuid
	*/
	EndpointID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put endpoint endpoint ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEndpointEndpointIDParams) WithDefaults() *PutEndpointEndpointIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put endpoint endpoint ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEndpointEndpointIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) WithTimeout(timeout time.Duration) *PutEndpointEndpointIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) WithContext(ctx context.Context) *PutEndpointEndpointIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) WithHTTPClient(client *http.Client) *PutEndpointEndpointIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) WithBody(body PutEndpointEndpointIDBody) *PutEndpointEndpointIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) SetBody(body PutEndpointEndpointIDBody) {
	o.Body = body
}

// WithEndpointID adds the endpointID to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) WithEndpointID(endpointID strfmt.UUID) *PutEndpointEndpointIDParams {
	o.SetEndpointID(endpointID)
	return o
}

// SetEndpointID adds the endpointId to the put endpoint endpoint ID params
func (o *PutEndpointEndpointIDParams) SetEndpointID(endpointID strfmt.UUID) {
	o.EndpointID = endpointID
}

// WriteToRequest writes these params to a swagger request
func (o *PutEndpointEndpointIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param endpoint_id
	if err := r.SetPathParam("endpoint_id", o.EndpointID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
