# SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  exclusions:
    rules:
    - linters:
      - staticcheck
      text: "QF1008:"
