// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostServiceServiceIDMigrateParams creates a new PostServiceServiceIDMigrateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostServiceServiceIDMigrateParams() *PostServiceServiceIDMigrateParams {
	return &PostServiceServiceIDMigrateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostServiceServiceIDMigrateParamsWithTimeout creates a new PostServiceServiceIDMigrateParams object
// with the ability to set a timeout on a request.
func NewPostServiceServiceIDMigrateParamsWithTimeout(timeout time.Duration) *PostServiceServiceIDMigrateParams {
	return &PostServiceServiceIDMigrateParams{
		timeout: timeout,
	}
}

// NewPostServiceServiceIDMigrateParamsWithContext creates a new PostServiceServiceIDMigrateParams object
// with the ability to set a context for a request.
func NewPostServiceServiceIDMigrateParamsWithContext(ctx context.Context) *PostServiceServiceIDMigrateParams {
	return &PostServiceServiceIDMigrateParams{
		Context: ctx,
	}
}

// NewPostServiceServiceIDMigrateParamsWithHTTPClient creates a new PostServiceServiceIDMigrateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostServiceServiceIDMigrateParamsWithHTTPClient(client *http.Client) *PostServiceServiceIDMigrateParams {
	return &PostServiceServiceIDMigrateParams{
		HTTPClient: client,
	}
}

/*
PostServiceServiceIDMigrateParams contains all the parameters to send to the API endpoint

	for the post service service ID migrate operation.

	Typically these are written to a http.Request.
*/
type PostServiceServiceIDMigrateParams struct {

	// Body.
	Body PostServiceServiceIDMigrateBody

	/* ServiceID.

	   The UUID of the service

	   Format: uuid
	*/
	ServiceID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post service service ID migrate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServiceServiceIDMigrateParams) WithDefaults() *PostServiceServiceIDMigrateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post service service ID migrate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServiceServiceIDMigrateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) WithTimeout(timeout time.Duration) *PostServiceServiceIDMigrateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) WithContext(ctx context.Context) *PostServiceServiceIDMigrateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) WithHTTPClient(client *http.Client) *PostServiceServiceIDMigrateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) WithBody(body PostServiceServiceIDMigrateBody) *PostServiceServiceIDMigrateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) SetBody(body PostServiceServiceIDMigrateBody) {
	o.Body = body
}

// WithServiceID adds the serviceID to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) WithServiceID(serviceID strfmt.UUID) *PostServiceServiceIDMigrateParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the post service service ID migrate params
func (o *PostServiceServiceIDMigrateParams) SetServiceID(serviceID strfmt.UUID) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *PostServiceServiceIDMigrateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
