// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/archer/models"
)

// PutServiceServiceIDReader is a Reader for the PutServiceServiceID structure.
type PutServiceServiceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutServiceServiceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutServiceServiceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutServiceServiceIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutServiceServiceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutServiceServiceIDOK creates a PutServiceServiceIDOK with default headers values
func NewPutServiceServiceIDOK() *PutServiceServiceIDOK {
	return &PutServiceServiceIDOK{}
}

/*
PutServiceServiceIDOK describes a response with status code 200, with default header values.

Service
*/
type PutServiceServiceIDOK struct {
	Payload *models.Service
}

// IsSuccess returns true when this put service service Id o k response has a 2xx status code
func (o *PutServiceServiceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put service service Id o k response has a 3xx status code
func (o *PutServiceServiceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put service service Id o k response has a 4xx status code
func (o *PutServiceServiceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put service service Id o k response has a 5xx status code
func (o *PutServiceServiceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put service service Id o k response a status code equal to that given
func (o *PutServiceServiceIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put service service Id o k response
func (o *PutServiceServiceIDOK) Code() int {
	return 200
}

func (o *PutServiceServiceIDOK) Error() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdOK  %+v", 200, o.Payload)
}

func (o *PutServiceServiceIDOK) String() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdOK  %+v", 200, o.Payload)
}

func (o *PutServiceServiceIDOK) GetPayload() *models.Service {
	return o.Payload
}

func (o *PutServiceServiceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Service)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutServiceServiceIDBadRequest creates a PutServiceServiceIDBadRequest with default headers values
func NewPutServiceServiceIDBadRequest() *PutServiceServiceIDBadRequest {
	return &PutServiceServiceIDBadRequest{}
}

/*
PutServiceServiceIDBadRequest describes a response with status code 400, with default header values.

Validation Error
*/
type PutServiceServiceIDBadRequest struct {
}

// IsSuccess returns true when this put service service Id bad request response has a 2xx status code
func (o *PutServiceServiceIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put service service Id bad request response has a 3xx status code
func (o *PutServiceServiceIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put service service Id bad request response has a 4xx status code
func (o *PutServiceServiceIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put service service Id bad request response has a 5xx status code
func (o *PutServiceServiceIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put service service Id bad request response a status code equal to that given
func (o *PutServiceServiceIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put service service Id bad request response
func (o *PutServiceServiceIDBadRequest) Code() int {
	return 400
}

func (o *PutServiceServiceIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdBadRequest ", 400)
}

func (o *PutServiceServiceIDBadRequest) String() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdBadRequest ", 400)
}

func (o *PutServiceServiceIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutServiceServiceIDNotFound creates a PutServiceServiceIDNotFound with default headers values
func NewPutServiceServiceIDNotFound() *PutServiceServiceIDNotFound {
	return &PutServiceServiceIDNotFound{}
}

/*
PutServiceServiceIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutServiceServiceIDNotFound struct {
}

// IsSuccess returns true when this put service service Id not found response has a 2xx status code
func (o *PutServiceServiceIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put service service Id not found response has a 3xx status code
func (o *PutServiceServiceIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put service service Id not found response has a 4xx status code
func (o *PutServiceServiceIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put service service Id not found response has a 5xx status code
func (o *PutServiceServiceIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put service service Id not found response a status code equal to that given
func (o *PutServiceServiceIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put service service Id not found response
func (o *PutServiceServiceIDNotFound) Code() int {
	return 404
}

func (o *PutServiceServiceIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdNotFound ", 404)
}

func (o *PutServiceServiceIDNotFound) String() string {
	return fmt.Sprintf("[PUT /service/{service_id}][%d] putServiceServiceIdNotFound ", 404)
}

func (o *PutServiceServiceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
