// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAgentsAgentHostParams creates a new GetAgentsAgentHostParams object
//
// There are no default values defined in the spec.
func NewGetAgentsAgentHostParams() GetAgentsAgentHostParams {

	return GetAgentsAgentHostParams{}
}

// GetAgentsAgentHostParams contains all the bound params for the get agents agent host operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAgentsAgentHost
type GetAgentsAgentHostParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The hostname of the agent
	  Required: true
	  In: path
	*/
	AgentHost string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAgentsAgentHostParams() beforehand.
func (o *GetAgentsAgentHostParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAgentHost, rhkAgentHost, _ := route.Params.GetOK("agent_host")
	if err := o.bindAgentHost(rAgentHost, rhkAgentHost, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAgentHost binds and validates parameter AgentHost from path.
func (o *GetAgentsAgentHostParams) bindAgentHost(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.AgentHost = raw

	return nil
}
