// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewDeleteRbacPoliciesRbacPolicyIDParams creates a new DeleteRbacPoliciesRbacPolicyIDParams object
//
// There are no default values defined in the spec.
func NewDeleteRbacPoliciesRbacPolicyIDParams() DeleteRbacPoliciesRbacPolicyIDParams {

	return DeleteRbacPoliciesRbacPolicyIDParams{}
}

// DeleteRbacPoliciesRbacPolicyIDParams contains all the bound params for the delete rbac policies rbac policy ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteRbacPoliciesRbacPolicyID
type DeleteRbacPoliciesRbacPolicyIDParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The UUID of the RBAC policy.
	  Required: true
	  In: path
	*/
	RbacPolicyID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteRbacPoliciesRbacPolicyIDParams() beforehand.
func (o *DeleteRbacPoliciesRbacPolicyIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRbacPolicyID, rhkRbacPolicyID, _ := route.Params.GetOK("rbac_policy_id")
	if err := o.bindRbacPolicyID(rRbacPolicyID, rhkRbacPolicyID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRbacPolicyID binds and validates parameter RbacPolicyID from path.
func (o *DeleteRbacPoliciesRbacPolicyIDParams) bindRbacPolicyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("rbac_policy_id", "path", "strfmt.UUID", raw)
	}
	o.RbacPolicyID = *(value.(*strfmt.UUID))

	if err := o.validateRbacPolicyID(formats); err != nil {
		return err
	}

	return nil
}

// validateRbacPolicyID carries out validations for parameter RbacPolicyID
func (o *DeleteRbacPoliciesRbacPolicyIDParams) validateRbacPolicyID(formats strfmt.Registry) error {

	if err := validate.FormatOf("rbac_policy_id", "path", "uuid", o.RbacPolicyID.String(), formats); err != nil {
		return err
	}
	return nil
}
