// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRbacPoliciesOKCode is the HTTP code returned for type GetRbacPoliciesOK
const GetRbacPoliciesOKCode int = 200

/*
GetRbacPoliciesOK A JSON array of rbac policies

swagger:response getRbacPoliciesOK
*/
type GetRbacPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *GetRbacPoliciesOKBody `json:"body,omitempty"`
}

// NewGetRbacPoliciesOK creates GetRbacPoliciesOK with default headers values
func NewGetRbacPoliciesOK() *GetRbacPoliciesOK {

	return &GetRbacPoliciesOK{}
}

// WithPayload adds the payload to the get rbac policies o k response
func (o *GetRbacPoliciesOK) WithPayload(payload *GetRbacPoliciesOKBody) *GetRbacPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rbac policies o k response
func (o *GetRbacPoliciesOK) SetPayload(payload *GetRbacPoliciesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRbacPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
