// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRbacPoliciesRbacPolicyIDHandlerFunc turns a function with the right signature into a get rbac policies rbac policy ID handler
type GetRbacPoliciesRbacPolicyIDHandlerFunc func(GetRbacPoliciesRbacPolicyIDParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRbacPoliciesRbacPolicyIDHandlerFunc) Handle(params GetRbacPoliciesRbacPolicyIDParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetRbacPoliciesRbacPolicyIDHandler interface for that can handle valid get rbac policies rbac policy ID params
type GetRbacPoliciesRbacPolicyIDHandler interface {
	Handle(GetRbacPoliciesRbacPolicyIDParams, any) middleware.Responder
}

// NewGetRbacPoliciesRbacPolicyID creates a new http.Handler for the get rbac policies rbac policy ID operation
func NewGetRbacPoliciesRbacPolicyID(ctx *middleware.Context, handler GetRbacPoliciesRbacPolicyIDHandler) *GetRbacPoliciesRbacPolicyID {
	return &GetRbacPoliciesRbacPolicyID{Context: ctx, Handler: handler}
}

/*
	GetRbacPoliciesRbacPolicyID swagger:route GET /rbac-policies/{rbac_policy_id} RBAC getRbacPoliciesRbacPolicyId

Show details of an RBAC policy
*/
type GetRbacPoliciesRbacPolicyID struct {
	Context *middleware.Context
	Handler GetRbacPoliciesRbacPolicyIDHandler
}

func (o *GetRbacPoliciesRbacPolicyID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRbacPoliciesRbacPolicyIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
