// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostRbacPoliciesHandlerFunc turns a function with the right signature into a post rbac policies handler
type PostRbacPoliciesHandlerFunc func(PostRbacPoliciesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRbacPoliciesHandlerFunc) Handle(params PostRbacPoliciesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRbacPoliciesHandler interface for that can handle valid post rbac policies params
type PostRbacPoliciesHandler interface {
	Handle(PostRbacPoliciesParams, interface{}) middleware.Responder
}

// NewPostRbacPolicies creates a new http.Handler for the post rbac policies operation
func NewPostRbacPolicies(ctx *middleware.Context, handler PostRbacPoliciesHandler) *PostRbacPolicies {
	return &PostRbacPolicies{Context: ctx, Handler: handler}
}

/*
	PostRbacPolicies swagger:route POST /rbac-policies RBAC postRbacPolicies

Create RBAC policy
*/
type PostRbacPolicies struct {
	Context *middleware.Context
	Handler PostRbacPoliciesHandler
}

func (o *PostRbacPolicies) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostRbacPoliciesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
