// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutRbacPoliciesRbacPolicyIDHandlerFunc turns a function with the right signature into a put rbac policies rbac policy ID handler
type PutRbacPoliciesRbacPolicyIDHandlerFunc func(PutRbacPoliciesRbacPolicyIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutRbacPoliciesRbacPolicyIDHandlerFunc) Handle(params PutRbacPoliciesRbacPolicyIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutRbacPoliciesRbacPolicyIDHandler interface for that can handle valid put rbac policies rbac policy ID params
type PutRbacPoliciesRbacPolicyIDHandler interface {
	Handle(PutRbacPoliciesRbacPolicyIDParams, interface{}) middleware.Responder
}

// NewPutRbacPoliciesRbacPolicyID creates a new http.Handler for the put rbac policies rbac policy ID operation
func NewPutRbacPoliciesRbacPolicyID(ctx *middleware.Context, handler PutRbacPoliciesRbacPolicyIDHandler) *PutRbacPoliciesRbacPolicyID {
	return &PutRbacPoliciesRbacPolicyID{Context: ctx, Handler: handler}
}

/*
	PutRbacPoliciesRbacPolicyID swagger:route PUT /rbac-policies/{rbac_policy_id} RBAC putRbacPoliciesRbacPolicyId

Update an existing RBAC policy
*/
type PutRbacPoliciesRbacPolicyID struct {
	Context *middleware.Context
	Handler PutRbacPoliciesRbacPolicyIDHandler
}

func (o *PutRbacPoliciesRbacPolicyID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutRbacPoliciesRbacPolicyIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
