// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	stderrors "errors"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/archer/models"
)

// GetQuotasHandlerFunc turns a function with the right signature into a get quotas handler
type GetQuotasHandlerFunc func(GetQuotasParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQuotasHandlerFunc) Handle(params GetQuotasParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetQuotasHandler interface for that can handle valid get quotas params
type GetQuotasHandler interface {
	Handle(GetQuotasParams, any) middleware.Responder
}

// NewGetQuotas creates a new http.Handler for the get quotas operation
func NewGetQuotas(ctx *middleware.Context, handler GetQuotasHandler) *GetQuotas {
	return &GetQuotas{Context: ctx, Handler: handler}
}

/*
	GetQuotas swagger:route GET /quotas Quota getQuotas

List Quotas
*/
type GetQuotas struct {
	Context *middleware.Context
	Handler GetQuotasHandler
}

func (o *GetQuotas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetQuotasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetQuotasOKBody get quotas o k body
//
// swagger:model GetQuotasOKBody
type GetQuotasOKBody struct {

	// links
	Links []*models.Link `json:"links,omitempty"`

	// quotas
	Quotas []*GetQuotasOKBodyQuotasItems0 `json:"quotas"`
}

// Validate validates this get quotas o k body
func (o *GetQuotasOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQuotas(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQuotasOKBody) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	for i := 0; i < len(o.Links); i++ {
		if swag.IsZero(o.Links[i]) { // not required
			continue
		}

		if o.Links[i] != nil {
			if err := o.Links[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getQuotasOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getQuotasOK" + "." + "links" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *GetQuotasOKBody) validateQuotas(formats strfmt.Registry) error {
	if swag.IsZero(o.Quotas) { // not required
		return nil
	}

	for i := 0; i < len(o.Quotas); i++ {
		if swag.IsZero(o.Quotas[i]) { // not required
			continue
		}

		if o.Quotas[i] != nil {
			if err := o.Quotas[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getQuotasOK" + "." + "quotas" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getQuotasOK" + "." + "quotas" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get quotas o k body based on the context it is used
func (o *GetQuotasOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateQuotas(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQuotasOKBody) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Links); i++ {

		if o.Links[i] != nil {

			if swag.IsZero(o.Links[i]) { // not required
				return nil
			}

			if err := o.Links[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getQuotasOK" + "." + "links" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getQuotasOK" + "." + "links" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *GetQuotasOKBody) contextValidateQuotas(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Quotas); i++ {

		if o.Quotas[i] != nil {

			if swag.IsZero(o.Quotas[i]) { // not required
				return nil
			}

			if err := o.Quotas[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getQuotasOK" + "." + "quotas" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getQuotasOK" + "." + "quotas" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotasOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotasOKBody) UnmarshalBinary(b []byte) error {
	var res GetQuotasOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetQuotasOKBodyQuotasItems0 get quotas o k body quotas items0
//
// swagger:model GetQuotasOKBodyQuotasItems0
type GetQuotasOKBodyQuotasItems0 struct {
	models.Quota

	models.QuotaUsage

	// project id
	ProjectID models.Project `json:"project_id"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetQuotasOKBodyQuotasItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 models.Quota
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	o.Quota = aO0

	// AO1
	var aO1 models.QuotaUsage
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	o.QuotaUsage = aO1

	// AO2
	var dataAO2 struct {
		ProjectID models.Project `json:"project_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	o.ProjectID = dataAO2.ProjectID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetQuotasOKBodyQuotasItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(o.Quota)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(o.QuotaUsage)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	var dataAO2 struct {
		ProjectID models.Project `json:"project_id"`
	}

	dataAO2.ProjectID = o.ProjectID

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get quotas o k body quotas items0
func (o *GetQuotasOKBodyQuotasItems0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Quota
	if err := o.Quota.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with models.QuotaUsage
	if err := o.QuotaUsage.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQuotasOKBodyQuotasItems0) validateProjectID(formats strfmt.Registry) error {

	if swag.IsZero(o.ProjectID) { // not required
		return nil
	}

	if err := o.ProjectID.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("project_id")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("project_id")
		}

		return err
	}

	return nil
}

// ContextValidate validate this get quotas o k body quotas items0 based on the context it is used
func (o *GetQuotasOKBodyQuotasItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Quota
	if err := o.Quota.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with models.QuotaUsage
	if err := o.QuotaUsage.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateProjectID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQuotasOKBodyQuotasItems0) contextValidateProjectID(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(o.ProjectID) { // not required
		return nil
	}

	if err := o.ProjectID.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("project_id")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("project_id")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetQuotasOKBodyQuotasItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQuotasOKBodyQuotasItems0) UnmarshalBinary(b []byte) error {
	var res GetQuotasOKBodyQuotasItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
