// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/archer/models"
)

// GetQuotasOKCode is the HTTP code returned for type GetQuotasOK
const GetQuotasOKCode int = 200

/*
GetQuotasOK A JSON array of quotas

swagger:response getQuotasOK
*/
type GetQuotasOK struct {

	/*
	  In: Body
	*/
	Payload *GetQuotasOKBody `json:"body,omitempty"`
}

// NewGetQuotasOK creates GetQuotasOK with default headers values
func NewGetQuotasOK() *GetQuotasOK {

	return &GetQuotasOK{}
}

// WithPayload adds the payload to the get quotas o k response
func (o *GetQuotasOK) WithPayload(payload *GetQuotasOKBody) *GetQuotasOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas o k response
func (o *GetQuotasOK) SetPayload(payload *GetQuotasOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetQuotasUnauthorizedCode is the HTTP code returned for type GetQuotasUnauthorized
const GetQuotasUnauthorizedCode int = 401

/*
GetQuotasUnauthorized Unauthorized

swagger:response getQuotasUnauthorized
*/
type GetQuotasUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetQuotasUnauthorized creates GetQuotasUnauthorized with default headers values
func NewGetQuotasUnauthorized() *GetQuotasUnauthorized {

	return &GetQuotasUnauthorized{}
}

// WithPayload adds the payload to the get quotas unauthorized response
func (o *GetQuotasUnauthorized) WithPayload(payload *models.Error) *GetQuotasUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas unauthorized response
func (o *GetQuotasUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetQuotasForbiddenCode is the HTTP code returned for type GetQuotasForbidden
const GetQuotasForbiddenCode int = 403

/*
GetQuotasForbidden Forbidden

swagger:response getQuotasForbidden
*/
type GetQuotasForbidden struct {
}

// NewGetQuotasForbidden creates GetQuotasForbidden with default headers values
func NewGetQuotasForbidden() *GetQuotasForbidden {

	return &GetQuotasForbidden{}
}

// WriteResponse to the client
func (o *GetQuotasForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetQuotasNotFoundCode is the HTTP code returned for type GetQuotasNotFound
const GetQuotasNotFoundCode int = 404

/*
GetQuotasNotFound Not Found

swagger:response getQuotasNotFound
*/
type GetQuotasNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetQuotasNotFound creates GetQuotasNotFound with default headers values
func NewGetQuotasNotFound() *GetQuotasNotFound {

	return &GetQuotasNotFound{}
}

// WithPayload adds the payload to the get quotas not found response
func (o *GetQuotasNotFound) WithPayload(payload *models.Error) *GetQuotasNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas not found response
func (o *GetQuotasNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetQuotasUnprocessableEntityCode is the HTTP code returned for type GetQuotasUnprocessableEntity
const GetQuotasUnprocessableEntityCode int = 422

/*
GetQuotasUnprocessableEntity Unprocessable Content

swagger:response getQuotasUnprocessableEntity
*/
type GetQuotasUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetQuotasUnprocessableEntity creates GetQuotasUnprocessableEntity with default headers values
func NewGetQuotasUnprocessableEntity() *GetQuotasUnprocessableEntity {

	return &GetQuotasUnprocessableEntity{}
}

// WithPayload adds the payload to the get quotas unprocessable entity response
func (o *GetQuotasUnprocessableEntity) WithPayload(payload *models.Error) *GetQuotasUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas unprocessable entity response
func (o *GetQuotasUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
