// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteEndpointEndpointIDNoContentCode is the HTTP code returned for type DeleteEndpointEndpointIDNoContent
const DeleteEndpointEndpointIDNoContentCode int = 204

/*
DeleteEndpointEndpointIDNoContent Resource successfully deleted.

swagger:response deleteEndpointEndpointIdNoContent
*/
type DeleteEndpointEndpointIDNoContent struct {
}

// NewDeleteEndpointEndpointIDNoContent creates DeleteEndpointEndpointIDNoContent with default headers values
func NewDeleteEndpointEndpointIDNoContent() *DeleteEndpointEndpointIDNoContent {

	return &DeleteEndpointEndpointIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteEndpointEndpointIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteEndpointEndpointIDNotFoundCode is the HTTP code returned for type DeleteEndpointEndpointIDNotFound
const DeleteEndpointEndpointIDNotFoundCode int = 404

/*
DeleteEndpointEndpointIDNotFound Not Found

swagger:response deleteEndpointEndpointIdNotFound
*/
type DeleteEndpointEndpointIDNotFound struct {
}

// NewDeleteEndpointEndpointIDNotFound creates DeleteEndpointEndpointIDNotFound with default headers values
func NewDeleteEndpointEndpointIDNotFound() *DeleteEndpointEndpointIDNotFound {

	return &DeleteEndpointEndpointIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteEndpointEndpointIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
