// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ServiceStatus Status of the service.
//
// ### Status can be one of
// | Status           | Description                            |
// | ---------------- | -------------------------------------- |
// | AVAILABLE        | Service is ready for consumption.      |
// | PENDING_CREATE   | Service is being set up                |
// | PENDING_UPDATE   | Service is being updated               |
// | PENDING_DELETE   | Service is being deleted               |
// | UNAVAILABLE      | Service is unavailable (e.g. disabled) |
// | ERROR_QUOTA      | Service has not enough port quota      |
//
// swagger:model ServiceStatus
type ServiceStatus string

func NewServiceStatus(value ServiceStatus) *ServiceStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ServiceStatus.
func (m ServiceStatus) Pointer() *ServiceStatus {
	return &m
}

const (

	// ServiceStatusAVAILABLE captures enum value "AVAILABLE"
	ServiceStatusAVAILABLE ServiceStatus = "AVAILABLE"

	// ServiceStatusPENDINGCREATE captures enum value "PENDING_CREATE"
	ServiceStatusPENDINGCREATE ServiceStatus = "PENDING_CREATE"

	// ServiceStatusPENDINGUPDATE captures enum value "PENDING_UPDATE"
	ServiceStatusPENDINGUPDATE ServiceStatus = "PENDING_UPDATE"

	// ServiceStatusPENDINGDELETE captures enum value "PENDING_DELETE"
	ServiceStatusPENDINGDELETE ServiceStatus = "PENDING_DELETE"

	// ServiceStatusUNAVAILABLE captures enum value "UNAVAILABLE"
	ServiceStatusUNAVAILABLE ServiceStatus = "UNAVAILABLE"

	// ServiceStatusERRORQUOTA captures enum value "ERROR_QUOTA"
	ServiceStatusERRORQUOTA ServiceStatus = "ERROR_QUOTA"
)

// for schema
var serviceStatusEnum []any

func init() {
	var res []ServiceStatus
	if err := json.Unmarshal([]byte(`["AVAILABLE","PENDING_CREATE","PENDING_UPDATE","PENDING_DELETE","UNAVAILABLE","ERROR_QUOTA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceStatusEnum = append(serviceStatusEnum, v)
	}
}

func (m ServiceStatus) validateServiceStatusEnum(path, location string, value ServiceStatus) error {
	if err := validate.EnumCase(path, location, value, serviceStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this service status
func (m ServiceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateServiceStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this service status based on the context it is used
func (m ServiceStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := validate.ReadOnly(ctx, "", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
