// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Service service
//
// swagger:model Service
type Service struct {

	// Availability zone of this service. If set to null, the service will be configured as a cross-AZ (cross-availability-zone) service, providing redundancy across all availability zones. Cross-AZ services are only supported in specific regions and providers that have cross-AZ agents deployed. If no cross-AZ agent is available for the requested region/provider, service creation will fail with a "No available host agent found" error.
	// Example: AZ-A
	// Max Length: 64
	AvailabilityZone *string `json:"availability_zone"`

	// created at
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Description of the service.
	// Example: An example of an Service.
	// Max Length: 255
	Description string `json:"description"`

	// Enable/disable this service. Existing endpoints are not touched by this.
	Enabled *bool `json:"enabled,omitempty"`

	// Health monitor status of the service backend.
	//
	// ### Health status can be one of
	// | Status      | Description                              |
	// | ----------- | ---------------------------------------- |
	// | ONLINE      | Service is healthy                       |
	// | DEGRADED    | Service is partially healthy             |
	// | OFFLINE     | Service is not healthy                   |
	// | UNCHECKED   | Status cannot be determined              |
	//
	// Read Only: true
	// Enum: ["ONLINE","DEGRADED","OFFLINE","UNCHECKED"]
	HealthStatus *string `json:"health_status,omitempty"`

	// Device host.
	// Read Only: true
	// Max Length: 64
	Host *string `json:"host,omitempty"`

	// The ID of the resource.
	// Read Only: true
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// IP Addresses of the providing service, multiple addresses will be round robin load balanced.
	// Required: true
	// Min Items: 1
	IPAddresses []strfmt.IPv4 `json:"ip_addresses"`

	// Name of the service.
	// Example: ExampleService
	// Max Length: 64
	Name string `json:"name"`

	// Network ID of the network that provides this service. Required for tenant provider, optional for cp provider.
	// Format: uuid
	NetworkID *strfmt.UUID `json:"network_id,omitempty"`

	// Ports exposed by the service.
	// Required: true
	// Min Items: 1
	// Unique: true
	Ports []int32 `json:"ports"`

	// project id
	ProjectID Project `json:"project_id"`

	// Protocol type of the service.
	//
	// ### protocol can be one of
	// | protocol         | Description                            |
	// | ---------------- | -------------------------------------- |
	// | HTTP             | Service is HTTP based                  |
	// | TCP              | Service is TCP based                   |
	//
	// Enum: ["HTTP","TCP"]
	Protocol *string `json:"protocol,omitempty"`

	// Provider type, defaults to tenant type.
	// Enum: ["tenant","cp"]
	Provider *string `json:"provider,omitempty"`

	// Proxy protocol v2 enabled for this service.
	ProxyProtocol *bool `json:"proxy_protocol,omitempty"`

	// Require explicit project approval for the service owner.
	RequireApproval *bool `json:"require_approval,omitempty"`

	// status
	Status ServiceStatus `json:"status,omitempty"`

	// The list of tags on the resource.
	Tags []string `json:"tags"`

	// updated at
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// Set global visibility of the service. For `private` visibility, RBAC policies can extend the visibility to specific projects.
	// Enum: ["private","public"]
	Visibility *string `json:"visibility,omitempty"`
}

// Validate validates this service
func (m *Service) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailabilityZone(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHealthStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIPAddresses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePorts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Service) validateAvailabilityZone(formats strfmt.Registry) error {
	if swag.IsZero(m.AvailabilityZone) { // not required
		return nil
	}

	if err := validate.MaxLength("availability_zone", "body", *m.AvailabilityZone, 64); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	return nil
}

func (m *Service) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 255); err != nil {
		return err
	}

	return nil
}

var serviceTypeHealthStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ONLINE","DEGRADED","OFFLINE","UNCHECKED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceTypeHealthStatusPropEnum = append(serviceTypeHealthStatusPropEnum, v)
	}
}

const (

	// ServiceHealthStatusONLINE captures enum value "ONLINE"
	ServiceHealthStatusONLINE string = "ONLINE"

	// ServiceHealthStatusDEGRADED captures enum value "DEGRADED"
	ServiceHealthStatusDEGRADED string = "DEGRADED"

	// ServiceHealthStatusOFFLINE captures enum value "OFFLINE"
	ServiceHealthStatusOFFLINE string = "OFFLINE"

	// ServiceHealthStatusUNCHECKED captures enum value "UNCHECKED"
	ServiceHealthStatusUNCHECKED string = "UNCHECKED"
)

// prop value enum
func (m *Service) validateHealthStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serviceTypeHealthStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Service) validateHealthStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.HealthStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateHealthStatusEnum("health_status", "body", *m.HealthStatus); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateHost(formats strfmt.Registry) error {
	if swag.IsZero(m.Host) { // not required
		return nil
	}

	if err := validate.MaxLength("host", "body", *m.Host, 64); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateIPAddresses(formats strfmt.Registry) error {

	if err := validate.Required("ip_addresses", "body", m.IPAddresses); err != nil {
		return err
	}

	iIPAddressesSize := int64(len(m.IPAddresses))

	if err := validate.MinItems("ip_addresses", "body", iIPAddressesSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m.IPAddresses); i++ {

		if err := validate.FormatOf("ip_addresses"+"."+strconv.Itoa(i), "body", "ipv4", m.IPAddresses[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *Service) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MaxLength("name", "body", m.Name, 64); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateNetworkID(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkID) { // not required
		return nil
	}

	if err := validate.FormatOf("network_id", "body", "uuid", m.NetworkID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Service) validatePorts(formats strfmt.Registry) error {

	if err := validate.Required("ports", "body", m.Ports); err != nil {
		return err
	}

	iPortsSize := int64(len(m.Ports))

	if err := validate.MinItems("ports", "body", iPortsSize, 1); err != nil {
		return err
	}

	if err := validate.UniqueItems("ports", "body", m.Ports); err != nil {
		return err
	}

	for i := 0; i < len(m.Ports); i++ {

		if err := validate.MinimumInt("ports"+"."+strconv.Itoa(i), "body", int64(m.Ports[i]), 1, false); err != nil {
			return err
		}

		if err := validate.MaximumInt("ports"+"."+strconv.Itoa(i), "body", int64(m.Ports[i]), 65535, false); err != nil {
			return err
		}

	}

	return nil
}

func (m *Service) validateProjectID(formats strfmt.Registry) error {
	if swag.IsZero(m.ProjectID) { // not required
		return nil
	}

	if err := m.ProjectID.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("project_id")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("project_id")
		}

		return err
	}

	return nil
}

var serviceTypeProtocolPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["HTTP","TCP"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceTypeProtocolPropEnum = append(serviceTypeProtocolPropEnum, v)
	}
}

const (

	// ServiceProtocolHTTP captures enum value "HTTP"
	ServiceProtocolHTTP string = "HTTP"

	// ServiceProtocolTCP captures enum value "TCP"
	ServiceProtocolTCP string = "TCP"
)

// prop value enum
func (m *Service) validateProtocolEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serviceTypeProtocolPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Service) validateProtocol(formats strfmt.Registry) error {
	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtocolEnum("protocol", "body", *m.Protocol); err != nil {
		return err
	}

	return nil
}

var serviceTypeProviderPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["tenant","cp"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceTypeProviderPropEnum = append(serviceTypeProviderPropEnum, v)
	}
}

const (

	// ServiceProviderTenant captures enum value "tenant"
	ServiceProviderTenant string = "tenant"

	// ServiceProviderCp captures enum value "cp"
	ServiceProviderCp string = "cp"
)

// prop value enum
func (m *Service) validateProviderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serviceTypeProviderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Service) validateProvider(formats strfmt.Registry) error {
	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	// value enum
	if err := m.validateProviderEnum("provider", "body", *m.Provider); err != nil {
		return err
	}

	return nil
}

func (m *Service) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

func (m *Service) validateTags(formats strfmt.Registry) error {
	if swag.IsZero(m.Tags) { // not required
		return nil
	}

	for i := 0; i < len(m.Tags); i++ {

		if err := validate.MaxLength("tags"+"."+strconv.Itoa(i), "body", m.Tags[i], 128); err != nil {
			return err
		}

	}

	return nil
}

func (m *Service) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	return nil
}

var serviceTypeVisibilityPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["private","public"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceTypeVisibilityPropEnum = append(serviceTypeVisibilityPropEnum, v)
	}
}

const (

	// ServiceVisibilityPrivate captures enum value "private"
	ServiceVisibilityPrivate string = "private"

	// ServiceVisibilityPublic captures enum value "public"
	ServiceVisibilityPublic string = "public"
)

// prop value enum
func (m *Service) validateVisibilityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serviceTypeVisibilityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Service) validateVisibility(formats strfmt.Registry) error {
	if swag.IsZero(m.Visibility) { // not required
		return nil
	}

	// value enum
	if err := m.validateVisibilityEnum("visibility", "body", *m.Visibility); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this service based on the context it is used
func (m *Service) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHealthStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHost(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProjectID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Service) contextValidateHealthStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "health_status", "body", m.HealthStatus); err != nil {
		return err
	}

	return nil
}

func (m *Service) contextValidateHost(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "host", "body", m.Host); err != nil {
		return err
	}

	return nil
}

func (m *Service) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Service) contextValidateProjectID(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.ProjectID) { // not required
		return nil
	}

	if err := m.ProjectID.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("project_id")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("project_id")
		}

		return err
	}

	return nil
}

func (m *Service) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Service) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Service) UnmarshalBinary(b []byte) error {
	var res Service
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
